-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 06:36:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Gestion_Magasin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Gestion_Magasin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gestion_Magasin` DEFAULT CHARACTER SET utf8 ;
USE `Gestion_Magasin` ;

-- -----------------------------------------------------
-- Table `Gestion_Magasin`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Magasin`.`categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `avatar` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Gestion_Magasin`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Magasin`.`produit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `prix` DOUBLE NOT NULL,
  `quantite_disponible` INT NOT NULL,
  `img` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `categorie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produit_categorie_idx` (`categorie_id` ASC) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Gestion_Magasin`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Magasin`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(250) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `prenom` VARCHAR(250) NOT NULL,
  `telephone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `mot_de_passe` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Gestion_Magasin`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Magasin`.`commande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `type_de_paiement` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commande_client1_idx` (`client_id` ASC) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Gestion_Magasin`.`detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Magasin`.`detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantite` DOUBLE NOT NULL,
  `produit_id` INT NOT NULL,
  `commande_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ligne_commande_produit1_idx` (`produit_id` ASC) ,
  INDEX `fk_ligne_commande_commande1_idx` (`commande_id` ASC) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

USE `Gestion_Magasin` ;

-- -----------------------------------------------------
-- Placeholder table for view `Gestion_Magasin`.`commande_v`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Magasin`.`commande_v` (`id` INT, `date` INT, `type_de_paiement` INT, `client_id` INT, `nom` INT, `prenom` INT, `telephone` INT, `email` INT, `mot_de_passe` INT);

-- -----------------------------------------------------
-- Placeholder table for view `Gestion_Magasin`.`produit_v`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Magasin`.`produit_v` (`libelle` INT, `avatar` INT, `id` INT, `designation` INT, `prix` INT, `quantite_disponible` INT, `img` INT, `categorie_id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `Gestion_Magasin`.`detail_v`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestion_Magasin`.`detail_v` (`libelle` INT, `avatar` INT, `prix` INT, `designation` INT, `img` INT, `quantite_disponible` INT, `categorie_id` INT, `id` INT, `quantite` INT, `produit_id` INT, `commande_id` INT, `date` INT, `type_de_paiement` INT, `client_id` INT, `nom` INT, `prenom` INT, `telephone` INT, `email` INT, `mot_de_passe` INT);

-- -----------------------------------------------------
-- View `Gestion_Magasin`.`commande_v`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gestion_Magasin`.`commande_v`;
USE `Gestion_Magasin`;
CREATE  OR REPLACE VIEW commande_v AS SELECT c.*,cl.nom,cl.prenom,cl.telephone,cl.email,cl.mot_de_passe FROM commande c,client cl where c.client_id = cl.id;

-- -----------------------------------------------------
-- View `Gestion_Magasin`.`produit_v`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gestion_Magasin`.`produit_v`;
USE `Gestion_Magasin`;
CREATE  OR REPLACE VIEW `produit_v` AS SELECT c.libelle, c.avatar, p.* FROM categorie c,produit p where c.id = p.categorie_id;

-- -----------------------------------------------------
-- View `Gestion_Magasin`.`detail_v`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Gestion_Magasin`.`detail_v`;
USE `Gestion_Magasin`;
CREATE  OR REPLACE VIEW detail_v as SELECT p.libelle,p.avatar,p.prix,p.designation,p.img,p.quantite_disponible,p.categorie_id,d.*,c.date,c.type_de_paiement,c.client_id,c.nom,c.prenom,c.telephone,c.email,c.mot_de_passe FROM produit_v p, commande_v c,detail d where p.id = d.produit_id AND c.id = d.commande_id;
USE `Gestion_Magasin`;

DELIMITER $$
USE `Gestion_Magasin`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Gestion_Magasin`.`categorie_BEFORE_DELETE` BEFORE DELETE ON `categorie` FOR EACH ROW
BEGIN
	DELETE FROM produit where categorie_id = OLD.id ;
END$$

USE `Gestion_Magasin`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Gestion_Magasin`.`produit_BEFORE_DELETE` BEFORE DELETE ON `produit` FOR EACH ROW
BEGIN
	DELETE FROM detail where produit_id = OLD.id;
END$$

USE `Gestion_Magasin`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Gestion_Magasin`.`client_BEFORE_DELETE` BEFORE DELETE ON `client` FOR EACH ROW
BEGIN
	DELETE FROM commande where client_id = OLD.id;
END$$

USE `Gestion_Magasin`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Gestion_Magasin`.`commande_BEFORE_DELETE` BEFORE DELETE ON `commande` FOR EACH ROW
BEGIN
	DELETE FROM detail WHERE commande_id = OLD.id ;
END$$

USE `Gestion_Magasin`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Gestion_Magasin`.`detail_AFTER_INSERT` AFTER INSERT ON `detail` FOR EACH ROW
BEGIN
	UPDATE produit SET quantite_disponible = quantite_disponible - NEW.quantite WHERE id = NEW.produit_id;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
